### ISSUE TITLE
Requester pays configuration in validator fails when used with requester pays configured buckets.

### ISSUE THREAD

**Issue by sharkinsspatial** [developmentseed/cdk-pgstac#12]
The requester pays configuration setting https://github.com/developmentseed/cdk-pgstac/blob/be40af70326f04d7ed9583569ad49f12da416d6f/lib/ingestor-api/runtime/src/validators.py#L34 defined in the validator fails with `Access Denied` when used against assets stored in requester pays buckets.  I temporarily updated this behavior to always use a `request payer` setting for all requests in https://github.com/developmentseed/cdk-pgstac/pull/8 in order to have a functional construct for testing.

**Comment by alukach** [comment]
@sharkinsspatial So when you hit the `Access Denied` issue, did you in fact have the `REQUESTER_PAYS` env flag set to something truthy?

**Comment by sharkinsspatial** [comment]
@alukach It is a bit fuzzy since I was simultaneously diagnosing the previous issue with the `settings` import, but I believe I explicitly hardcoded `settings.requester_pays = true` in the validator for verification testing rather than trying to pull it from the environment.  Is it working correctly for you?  I agree, I can't see any logic error here that would prevent `RequestPayer` from being passed and I even tested this successfully in an isolated cli application to verify.

**Comment by sharkinsspatial** [comment]
Closed by https://github.com/developmentseed/aws-asdi-pgstac/pull/17
