### ISSUE TITLE
Remove custom VEDA bootstrapping logic.

### ISSUE THREAD

**Issue by sharkinsspatial** [developmentseed/cdk-pgstac#28]
Our `pgstac` bootstrapping logic currently injects several [VEDA specific functions](https://github.com/developmentseed/cdk-pgstac/blob/main/lib/bootstrapper/runtime/handler.py#L148-L205).  With the [0.7 release of pgstac](https://github.com/stac-utils/pgstac/pull/160) we can use triggers to update collection extents so we can remove the custom VEDA logic.

**Comment by emileten** [comment]
@sharkinsspatial is it correct that this is about removing the[ three functions ingested here](https://github.com/developmentseed/cdk-pgstac/blob/4ef537c7ef5f3f7b8fd9b2cccd5e49633dd3aa3e/lib/bootstrapper/runtime/handler.py#L304), `create_dashboard_schema`, `create_update_default_summaries_function`, `create_update_all_default_summaries_function` ? 

It looks like we have to make sure we remove the use cases of these functions. For example, [when we load items](https://github.com/developmentseed/cdk-pgstac/blob/4ef537c7ef5f3f7b8fd9b2cccd5e49633dd3aa3e/lib/ingestor-api/runtime/src/utils.py#L55) we call a function that updates the collection summary [and makes use of these VEDA-specific ingested functions. ](https://github.com/developmentseed/cdk-pgstac/blob/4ef537c7ef5f3f7b8fd9b2cccd5e49633dd3aa3e/lib/ingestor-api/runtime/src/loader.py#L30).

Also, I am curious what this look would look like with this triggers feature ?
