### ISSUE TITLE
Separate out non-CDK related code

### ISSUE THREAD

**Issue by emileten** [developmentseed/cdk-pgstac#30]
from the title in the README, `cdk-pgstac` is a set of AWS CDK constructs that spin up AWS infrastructure to operate and use a `pgstac` database.

As such, any application it relies on shouldn't be defined in `cdk-pgstac`, but only used as an external dependency, so that `cdk-pgstac` focuses only on AWS CDK logic. 

From that perspective, the following application code that currently is located in this repository should be separated out : 
1. [the app that contains the logic to ingest records into the database](https://github.com/developmentseed/cdk-pgstac/tree/main/lib/ingestor-api/runtime) aka `ingestor-api`
2. [the app that contains the logic to query records from the database](https://github.com/developmentseed/cdk-pgstac/tree/main/lib/stac-api/runtime), aka `stac-api`. 
3. [the app that bootstraps the database](https://github.com/developmentseed/cdk-pgstac/tree/main/lib/bootstrapper/runtime).

I think @alukach already mentioned (1) in a previous call. Does this make sense to you ?

**Comment by emileten** [comment]
Actually this looks like a (partial?) duplicate of https://github.com/developmentseed/cdk-pgstac/issues/4.

**Comment by sharkinsspatial** [comment]
@emileten Our approach for building APIs has largely focused on building FastAPI applications.  One of their great advantages is the simplicity of having route logic defined internally in the application but still being able to support several different deployment targets, but this does require a some very thin [mangum](https://github.com/jordaneremieff/mangum) wrapping to support application deployment for the API Gateway/Lambda context.

The goal of of this `cdk-pgtstac` is to bring together all of the pieces required to have a functional STAC API (`pgstac`, 'stac-fastapi`, `ingestor-api`) into a simple deployable construct with some sensible defaults.  

As @alukach was building out the `ingestor-api` functionality, it made sense to directly package the `ingestor-api` code into this repo for development purposes but as mentioned in https://github.com/developmentseed/cdk-pgstac/issues/4 the goal is to extract this into a separate stand alone FastAPI application.

We will always some level of wrapping code that ties our deployment context (Lambda) and configuration to our FastAPI apps so having https://github.com/developmentseed/cdk-pgstac/tree/main/lib/stac-api/runtime will always be a necessity to simple things for construct users.

We'll use the same pattern as we incorporate https://github.com/stac-utils/titiler-pgstac into `cdk-pgstac` as well.  I'm going  to close this and we'll keep https://github.com/developmentseed/cdk-pgstac/issues/4 as the main issue.

**Comment by emileten** [comment]
Thanks for the reply @sharkinsspatial, I understand the logic and agree that 

> but as mentioned in https://github.com/developmentseed/cdk-pgstac/issues/4 the goal is to extract this into a separate stand alone FastAPI application.

is the piece that should be moved.
