### ISSUE TITLE
Make a new release by modifying last PR commit message

### ISSUE THREAD

**Issue by emileten** [developmentseed/cdk-pgstac#31]
I merged https://github.com/developmentseed/cdk-pgstac/pull/29 before understanding how the release works in this repository. 

My commit message was wrong, it was : 

```
refactor: remove VEDA logic (https://github.com/developmentseed/cdk-pgstac/pull/29)

* remove injected VEDA funcs and their usage instances

* flake8
```

Whereas it should have been (with the BREAKING change footer, plus the scope) -- this would have triggered the release and is actually right, I forgot to mention it's a breaking change. 

```
refactor(bootstrapper): remove VEDA logic (https://github.com/developmentseed/cdk-pgstac/pull/29)

* remove injected VEDA funcs and their usage instances

* flake8

BREAKING CHANGE: remove dashboard schema and functions from the database bootstrapper and remove automatic collection summary udpate from ingestor
```

I can fix that locally (checked on my personal fork) [by doing (more info)](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message): 
```
git commit --amend
.. add the BREAKING CHANGE footer ...
git push origin main --force-with-lease
```

This makes a new 3.0.0 release. Are people ok with this ? @alukach I tag you since you are the author of this repository. Maybe @sharkinsspatial has thoughts?

**Comment by alukach** [comment]
@emileten I think everything you're saying makes total sense.  I say go forth with the rebase, this project gets light-enough usage that you likely won't mess with anyone's work.

We're all still onboarding to Conventional Commits and automated versioning, so these things have definitely popped up in the past.  I'm still not certain that this is better or worse than manually managing versions.  The truth will tell.

**Comment by emileten** [comment]
Done: https://github.com/developmentseed/cdk-pgstac/releases/tag/v3.0.0

I think that automating this would be great. Although I admit it took me a while to figure out how it is supposed to work -- it doesn't help that there is no tool that comes out of the box to just check if the commit analyzer would like or not a given message -- the information is out there, so with an enhanced documentation in our side I think it would be useful : (1) make it clear _where_ in our actions yaml files the release happens and (2) have clear pointers to the documentation that tells what commits work or do not work.
