### ISSUE TITLE
Include titiler API endpoint.

### ISSUE THREAD

**Issue by sharkinsspatial** [developmentseed/cdk-pgstac#40]
As this construct becomes used across several projects we should incorporate an optional `titiler` API endpoint (with a `titiler-pgstac` extension).  Ideally, this would follow the same implementation pattern that we currently use for the [stac-api](https://github.com/developmentseed/cdk-pgstac/tree/main/lib/stac-api).

**Comment by emileten** [comment]
@sharkinsspatial have you started working on this ? In MAAP we're using cdk-pgstac, and we want to use the opportunity of deployment migration to consolidate on one tiler instance that we get from a reused common resource like this.

**Comment by emileten** [comment]
I think we can close -- a titiler API endpoint was added in https://github.com/developmentseed/cdk-pgstac/pull/42.
