### ISSUE TITLE
Getting urllib3 error on bootstrapper action

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/cdk-pgstac#44]
When deploying the bootstrapp custom resource which I believe is executing [bootstrapper/runtime/handler.py](https://github.com/developmentseed/cdk-pgstac/blob/main/lib/bootstrapper/runtime/handler.py) I get the following error:

lambda runtime: python3.8
```
2023-06-10T10:02:29.326-07:00Copy[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
Traceback (most recent call last): | [ERROR] Runtime.ImportModuleError: Unable to import module 'handler': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips 26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168 Traceback (most recent call last):
-- | --
```

From https://stackoverflow.com/questions/76187256/importerror-urllib3-v2-0-only-supports-openssl-1-1-1-currently-the-ssl-modu it appears the solution may be to pin the urllib version:

```
pip install urllib3==1.26.6 
```

I get a similar error with python3.9

```
Unable to import module 'handler': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)
```

**Comment by vincentsarago** [comment]
related to 
- https://github.com/NASA-IMPACT/veda-backend/pull/182
- https://github.com/NASA-IMPACT/veda-backend/pull/180#issuecomment-1558484686
- https://github.com/developmentseed/eoAPI/pull/71

**Comment by abarciauskas-bgse** [comment]
Thanks @vincentsarago - is there a reason not to:

* Add `"urllib3<2"` to https://github.com/developmentseed/cdk-pgstac/blob/main/lib/bootstrapper/runtime/Dockerfile#L8
* Use httpx

Should we do both like in https://github.com/NASA-IMPACT/veda-backend/pull/182/files ?

**Comment by vincentsarago** [comment]
I prefer personally `httpx` (because it supports both sync/async and is really well designed) but forcing `urllib3<2` should fix the issue short term!

**Comment by emileten** [comment]
Got the same error trying to deploy in a github action for MAAP. 

I bumped cdk-pgstac to pull https://github.com/developmentseed/cdk-pgstac/pull/45 and it solved it. I think we can close this.
